#!/usr/bin/env ruby
require "bundler/setup"
require "dry/cli"
require_relative "lib/commands"

module Rubosort
  module CLI
    module Commands
      extend Dry::CLI::Registry

      register "version", Version, aliases: ["v", "-v", "--version"]
      register "sort",    Sort, aliases: ["s", "-s", "--sort"]
    end
  end
end

Dry::CLI.new(Rubosort::CLI::Commands).call
